// Inventario de demostración. Se sirve en la web pública cuando Supabase
// no está configurado o no responde, para que el sitio nunca se vea vacío.
// Mantener sincronizado con supabase/seed.sql.

const img = (id, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`

const vehicleImages = (vehicleId, ids) =>
  ids.map((photoId, i) => ({
    id: `${vehicleId}-img-${i}`,
    vehicle_id: vehicleId,
    image_url: img(photoId),
    display_order: i,
    is_primary: i === 0,
  }))

const v = (overrides) => ({
  mileage: 0,
  fuel_type: 'Gasolina',
  transmission: 'Automática',
  doors: 4,
  condition: 'Usado',
  status: 'disponible',
  location: 'Santo Domingo, RD',
  featured: false,
  features: [],
  vin: null,
  instagram_url: null,
  inspection_notes: null,
  vehicle_history: 'Historial verificado, título limpio.',
  ...overrides,
})

export const DEMO_EXCHANGE_RATE = 61.25

export const DEMO_VEHICLES = [
  v({
    id: 'demo-amg-gt',
    created_at: '2026-05-28T14:00:00Z',
    brand: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2023,
    price_usd: 148500,
    mileage: 9800,
    engine: 'V8 Biturbo 4.0L · 577 HP',
    color: 'Gris Selenita',
    interior_color: 'Negro / Rojo',
    doors: 2,
    body_type: 'Coupe',
    featured: true,
    description:
      'Deportivo insignia de Mercedes-AMG. Motor V8 biturbo hecho a mano, escape deportivo AMG Performance y paquete aerodinámico de fábrica. Unidad importada con historial certificado.',
    features: [
      'Escape AMG Performance',
      'Asientos AMG en napa',
      'Burmester Surround',
      'Cámara 360°',
      'Paquete Noche AMG',
    ],
    vehicle_images: vehicleImages('demo-amg-gt', [
      'photo-1618843479313-40f8afb4b4d8',
      'photo-1617814076367-b759c7d7e738',
      'photo-1606220838315-056192d5e927',
    ]),
  }),
  v({
    id: 'demo-rr-sport',
    created_at: '2026-05-21T14:00:00Z',
    brand: 'Land Rover',
    model: 'Range Rover Sport HSE',
    year: 2024,
    price_usd: 112000,
    mileage: 6500,
    engine: 'I6 MHEV 3.0L · 395 HP',
    color: 'Negro Santorini',
    interior_color: 'Caramelo',
    body_type: 'SUV',
    featured: true,
    description:
      'Versatilidad británica con confort extremo. Suspensión neumática adaptativa, tracción total permanente y tercera fila opcional. Ideal para ciudad y montaña.',
    features: [
      'Suspensión neumática',
      'Meridian Signature',
      'Head-Up Display',
      'Asientos ventilados',
      'Terrain Response 2',
    ],
    vehicle_images: vehicleImages('demo-rr-sport', [
      'photo-1606664515524-ed2f786a0bd6',
      'photo-1605559424843-9e4c228bf1c2',
    ]),
  }),
  v({
    id: 'demo-porsche-911',
    created_at: '2026-05-15T14:00:00Z',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2022,
    price_usd: 139900,
    mileage: 14200,
    engine: 'Boxer 6 Biturbo 3.0L · 443 HP',
    color: 'Amarillo Racing',
    interior_color: 'Negro',
    doors: 2,
    body_type: 'Coupe',
    featured: true,
    description:
      'El ícono atemporal. PDK de 8 velocidades, paquete Sport Chrono y dirección trasera activa. Mantenimientos al día en casa de marca.',
    features: [
      'Sport Chrono',
      'PASM',
      'Escape deportivo',
      'BOSE Surround',
      'Llantas Carrera S 20/21"',
    ],
    vehicle_images: vehicleImages('demo-porsche-911', [
      'photo-1611821064430-0d40291d0f0b',
      'photo-1503376780353-7e6692767b70',
    ]),
  }),
  v({
    id: 'demo-lc300',
    created_at: '2026-05-30T14:00:00Z',
    brand: 'Toyota',
    model: 'Land Cruiser 300 VX',
    year: 2024,
    price_usd: 128000,
    mileage: 3200,
    fuel_type: 'Diesel',
    engine: 'V6 Twin-Turbo Diesel 3.3L · 304 HP',
    color: 'Blanco Perla',
    interior_color: 'Beige',
    body_type: 'SUV',
    condition: 'Nuevo',
    featured: true,
    description:
      'La referencia absoluta en SUV de lujo todoterreno para el mercado dominicano. Siete plazas, KDSS electrónico y fiabilidad legendaria.',
    features: [
      '7 plazas',
      'E-KDSS',
      'Multi-Terrain Select',
      'JBL Premium',
      'Asientos ventilados',
    ],
    vehicle_images: vehicleImages('demo-lc300', [
      'photo-1594502184342-2e12f877aa73',
      'photo-1568605117036-5fe5e7bab0b7',
    ]),
  }),
  v({
    id: 'demo-bmw-m4',
    created_at: '2026-05-08T14:00:00Z',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2023,
    price_usd: 96500,
    mileage: 11900,
    engine: 'I6 Biturbo 3.0L · 503 HP',
    color: 'Azul Portimao',
    interior_color: 'Negro / Azul',
    doors: 2,
    body_type: 'Coupe',
    description:
      'Precisión alemana en estado puro. M xDrive, frenos M Compound y asientos baquet M Carbon. Una máquina de manejo para el día a día.',
    features: [
      'M xDrive',
      'Asientos M Carbon',
      'Harman Kardon',
      'Laserlight',
      'M Drive Professional',
    ],
    vehicle_images: vehicleImages('demo-bmw-m4', [
      'photo-1555215695-3004980ad54e',
      'photo-1580273916550-e323be2ae537',
    ]),
  }),
  v({
    id: 'demo-tesla-m3',
    created_at: '2026-06-02T14:00:00Z',
    brand: 'Tesla',
    model: 'Model 3 Long Range',
    year: 2024,
    price_usd: 47900,
    mileage: 8400,
    fuel_type: 'Eléctrico',
    engine: 'Dual Motor AWD · 510 km autonomía',
    color: 'Rojo Multicapa',
    interior_color: 'Negro',
    body_type: 'Sedan',
    featured: true,
    description:
      'Cero combustible, cero mantenimiento complejo. Autopilot, techo panorámico de cristal y carga rápida. La puerta de entrada a la movilidad eléctrica premium.',
    features: [
      'Autopilot',
      'Techo de cristal',
      'Supercharging',
      'Premium Connectivity',
      'Sentry Mode',
    ],
    vehicle_images: vehicleImages('demo-tesla-m3', [
      'photo-1560958089-b8a1929cea89',
      'photo-1536700503339-1e4b06520771',
    ]),
  }),
  v({
    id: 'demo-hilux',
    created_at: '2026-05-25T14:00:00Z',
    brand: 'Toyota',
    model: 'Hilux SRV 4x4',
    year: 2023,
    price_usd: 42500,
    mileage: 26700,
    fuel_type: 'Diesel',
    engine: 'Turbo Diesel 2.8L · 201 HP',
    color: 'Gris Oscuro',
    interior_color: 'Negro',
    body_type: 'Pickup',
    description:
      'La pickup más confiable del país. Doble cabina, tracción 4x4 con bloqueo y cama protegida. Lista para trabajo o aventura.',
    features: [
      '4x4 con bloqueo',
      'Cámara de retroceso',
      'Control de descenso',
      'Bedliner',
      'Estribos laterales',
    ],
    vehicle_images: vehicleImages('demo-hilux', [
      'photo-1559416523-140ddc3d238c',
      'photo-1612544448445-b8232cff3b6c',
    ]),
  }),
  v({
    id: 'demo-crv',
    created_at: '2026-05-18T14:00:00Z',
    brand: 'Honda',
    model: 'CR-V EX-L',
    year: 2023,
    price_usd: 38900,
    mileage: 19500,
    fuel_type: 'Híbrido',
    engine: 'Híbrido e:HEV 2.0L · 204 HP',
    color: 'Plata Lunar',
    interior_color: 'Gris',
    body_type: 'SUV',
    description:
      'El SUV familiar por excelencia, ahora híbrido. Consumo mínimo en ciudad, Honda Sensing de serie y maletero gigante.',
    features: [
      'Honda Sensing',
      'Asientos en piel',
      'Portón eléctrico',
      'CarPlay/Android Auto',
      'Techo solar',
    ],
    vehicle_images: vehicleImages('demo-crv', [
      'photo-1568844293986-8d0400bd4745',
      'photo-1606016159991-dfe4f2746ad5',
    ]),
  }),
  v({
    id: 'demo-mustang',
    created_at: '2026-04-30T14:00:00Z',
    brand: 'Ford',
    model: 'Mustang GT Premium',
    year: 2022,
    price_usd: 56800,
    mileage: 17800,
    transmission: 'Manual',
    engine: 'V8 Coyote 5.0L · 450 HP',
    color: 'Rojo Race',
    interior_color: 'Negro',
    doors: 2,
    body_type: 'Convertible',
    status: 'reservado',
    description:
      'V8 atmosférico y caja manual de 6 velocidades: la combinación que ya casi no existe. Convertible, escape activo y modo pista.',
    features: [
      'Escape activo',
      'Modo pista',
      'Asientos Recaro',
      'B&O Sound',
      'Launch control',
    ],
    vehicle_images: vehicleImages('demo-mustang', [
      'photo-1584345604476-8ec5e12e42dd',
      'photo-1494976388531-d1058494cdd8',
    ]),
  }),
  v({
    id: 'demo-santafe',
    created_at: '2026-05-05T14:00:00Z',
    brand: 'Hyundai',
    model: 'Santa Fe Calligraphy',
    year: 2024,
    price_usd: 49500,
    mileage: 5100,
    engine: 'Turbo 2.5L · 281 HP',
    color: 'Verde Bosque Mate',
    interior_color: 'Camel',
    body_type: 'SUV',
    condition: 'Nuevo',
    description:
      'El nuevo diseño que está dando de qué hablar. Tres filas, interior tipo lounge y garantía de fábrica vigente.',
    features: [
      '7 plazas',
      'Doble pantalla curva 12.3"',
      'Asientos relax 2da fila',
      'Bose Premium',
      'Highway Drive Assist',
    ],
    vehicle_images: vehicleImages('demo-santafe', [
      'photo-1632245889029-e406faaa34cd',
      'photo-1519641471654-76ce0107ad1b',
    ]),
  }),
  v({
    id: 'demo-corolla',
    created_at: '2026-04-22T14:00:00Z',
    brand: 'Toyota',
    model: 'Corolla SE',
    year: 2022,
    price_usd: 24900,
    mileage: 31200,
    engine: '2.0L Dynamic Force · 169 HP',
    color: 'Blanco',
    interior_color: 'Negro',
    body_type: 'Sedan',
    description:
      'El sedán más vendido del mundo. Económico, confiable y con Toyota Safety Sense completo. Perfecto primer auto o flota ejecutiva.',
    features: [
      'Toyota Safety Sense',
      'Pantalla 8"',
      'Cámara de retroceso',
      'Llantas 18"',
      'Control crucero adaptativo',
    ],
    vehicle_images: vehicleImages('demo-corolla', [
      'photo-1623869675781-80aa31012a5a',
      'photo-1590362891991-f776e747a588',
    ]),
  }),
  v({
    id: 'demo-g63',
    created_at: '2026-04-12T14:00:00Z',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2021,
    price_usd: 189000,
    mileage: 22400,
    engine: 'V8 Biturbo 4.0L · 577 HP',
    color: 'Negro Obsidiana',
    interior_color: 'Rojo Clásico',
    doors: 5,
    body_type: 'SUV',
    status: 'vendido',
    description:
      'El G-Wagon que no necesita presentación. Vendido a un cliente de nuestra cartera — pregunta por unidades similares en camino.',
    features: [
      'Paquete Noche AMG',
      'Escape lateral AMG',
      'Burmester 3D',
      'Asientos masaje',
      'Multibeam LED',
    ],
    vehicle_images: vehicleImages('demo-g63', [
      'photo-1520031441872-265e4ff70366',
      'photo-1583121274602-3e2820c69888',
    ]),
  }),
]

export function getDemoVehicleById(id) {
  return DEMO_VEHICLES.find((vehicle) => vehicle.id === id) || null
}
